project_id = "savriwalgygixwtcpmya"

[functions.generate-wellness-plan]
verify_jwt = true

[functions.check-cycle-phase-changes]
verify_jwt = false

[functions.send-partner-reminders]
verify_jwt = false

[functions.predict-symptoms]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true